env:
  global:
    - RUST_BACKTRACE=1
    - PATH=$PATH:$HOME/.cargo/bin
    - RUST_RUSTFMT=0.99.2
    - RUST_CLIPPY=0.0.212
os:
  - linux
  - osx
language: rust
rust:
  - 1.28.0
  - nightly-2018-07-07
sudo: false
branches:
  only:
    - master
cache:
  cargo: true
before_script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/travis/cargo_install.sh > cargo_install.sh
  - bash cargo_install.sh cargo-prune;
  - if [[ $TRAVIS_RUST_VERSION =~ ^nightly.* && $TRAVIS_OS_NAME == linux ]]; then
      bash cargo_install.sh rustfmt-nightly "$RUST_RUSTFMT";
      bash cargo_install.sh clippy "$RUST_CLIPPY";
    fi
script:
  - if [[ ! $TRAVIS_RUST_VERSION =~ ^nightly.* ]]; then
      (
        set -x;
        cargo test --verbose --release &&
        cargo test --verbose --release --features mock &&
        cargo test --verbose --release --features mock -- --ignored print_seed_only_once_for_multiple_failures
      );
    elif [[ $TRAVIS_OS_NAME == linux ]]; then
      (
        set -x;
        cargo fmt -- --check &&
        cargo clippy --verbose --all-targets
      );
    fi
before_cache:
 - cargo prune
