[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A convenience library providing abstractions for cryptographic functions."
homepage = "https://maidsafe.net"
license = "MIT OR BSD-3-Clause"
name = "safe_crypto"
readme = "README.md"
repository = "https://github.com/maidsafe/safe_crypto"
version = "0.1.0"

[dependencies]
maidsafe_utilities = "~0.15.0"
quick-error = "~1.2.2"
rust_sodium = "~0.9.0"
serde = "~1.0.66"
serde_derive = "~1.0.66"
unwrap = "~1.1.0"
rand = { version = "~0.5.2", optional = true }
tiny-keccak = { version = "~1.4.2", optional = true }
x25519-dalek = { version = "~0.2.0", optional = true, default-features = false, features = ["u64_backend"] }

[dev-dependencies]
rand = "~0.5.2"

[features]
use-mock-crypto = ["rand", "tiny-keccak", "x25519-dalek"]
