[package]
name = "safe_crypto"
version = "0.1.0"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
license = "MIT OR BSD-3-Clause"

[dependencies]
maidsafe_utilities = "~0.14.0"
rust_sodium = "~0.9.0"
serde = "~1.0.66"
serde_derive = "~1.0.66"
quick-error = "~1.2.2"
unwrap = "~1.1.0"

